package pt.dourobats.app.core.ui.theme

import androidx.compose.ui.graphics.Color

// Kinetic Precision Design System - High-End Editorial Athletic Theme
// Creative North Star: "The Kinetic Gallery"

// Light Theme Colors
// Primary: Midnight Pitch (#001e40) - The deep blue of authority and professional athletics
val primaryLight = Color(0xFF001E40)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD4E3FF)
val onPrimaryContainerLight = Color(0xFF001C39)
val secondaryLight = Color(0xFF006E0A)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF75FF68)
val onSecondaryContainerLight = Color(0xFF002201)
val tertiaryLight = Color(0xFFFF7022)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDBCF)
val onTertiaryContainerLight = Color(0xFF3A1100)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF8F9FA)
val onBackgroundLight = Color(0xFF191C1D)
val surfaceLight = Color(0xFFF8F9FA)
val onSurfaceLight = Color(0xFF191C1D)
val surfaceVariantLight = Color(0xFFDFE2EB)
val onSurfaceVariantLight = Color(0xFF43474E)
val outlineLight = Color(0xFF73777F)
val outlineVariantLight = Color(0xFFC3C6CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3132)
val inverseOnSurfaceLight = Color(0xFFF0F1F2)
val inversePrimaryLight = Color(0xFFA6C8FF)
val surfaceDimLight = Color(0xFFD8DADB)
val surfaceBrightLight = Color(0xFFF8F9FA)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F4F5)
val surfaceContainerLight = Color(0xFFECEEEF)
val surfaceContainerHighLight = Color(0xFFE6E8E9)
val surfaceContainerHighestLight = Color(0xFFE1E2E4)

// Light Medium Contrast
val primaryLightMediumContrast = Color(0xFF001534)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF1A3658)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF005407)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF1B8520)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFFCC4F00)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFFFF8752)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF8F9FA)
val onBackgroundLightMediumContrast = Color(0xFF191C1D)
val surfaceLightMediumContrast = Color(0xFFF8F9FA)
val onSurfaceLightMediumContrast = Color(0xFF191C1D)
val surfaceVariantLightMediumContrast = Color(0xFFDFE2EB)
val onSurfaceVariantLightMediumContrast = Color(0xFF3F434A)
val outlineLightMediumContrast = Color(0xFF5B5F67)
val outlineVariantLightMediumContrast = Color(0xFF777B83)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2E3132)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF0F1F2)
val inversePrimaryLightMediumContrast = Color(0xFFA6C8FF)
val surfaceDimLightMediumContrast = Color(0xFFD8DADB)
val surfaceBrightLightMediumContrast = Color(0xFFF8F9FA)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF3F4F5)
val surfaceContainerLightMediumContrast = Color(0xFFE6E8E9)
val surfaceContainerHighLightMediumContrast = Color(0xFFE1E2E4)
val surfaceContainerHighestLightMediumContrast = Color(0xFFDBDCDE)

// Light High Contrast
val primaryLightHighContrast = Color(0xFF00101F)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF001534)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF002D02)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF005407)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF4D1700)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFFCC4F00)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF8F9FA)
val onBackgroundLightHighContrast = Color(0xFF191C1D)
val surfaceLightHighContrast = Color(0xFFF8F9FA)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDFE2EB)
val onSurfaceVariantLightHighContrast = Color(0xFF20242B)
val outlineLightHighContrast = Color(0xFF3F434A)
val outlineVariantLightHighContrast = Color(0xFF5B5F67)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2E3132)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFE3ECFF)
val surfaceDimLightHighContrast = Color(0xFFD8DADB)
val surfaceBrightLightHighContrast = Color(0xFFF8F9FA)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF3F4F5)
val surfaceContainerLightHighContrast = Color(0xFFE1E2E4)
val surfaceContainerHighLightHighContrast = Color(0xFFDBDCDE)
val surfaceContainerHighestLightHighContrast = Color(0xFFD5D7D8)

// Dark Theme Colors
val primaryDark = Color(0xFFA6C8FF)
val onPrimaryDark = Color(0xFF00315D)
val primaryContainerDark = Color(0xFF004783)
val onPrimaryContainerDark = Color(0xFFD4E3FF)
val secondaryDark = Color(0xFF5AE14F)
val onSecondaryDark = Color(0xFF003A03)
val secondaryContainerDark = Color(0xFF005306)
val onSecondaryContainerDark = Color(0xFF75FF68)
val tertiaryDark = Color(0xFFFFB599)
val onTertiaryDark = Color(0xFF5C2200)
val tertiaryContainerDark = Color(0xFF833800)
val onTertiaryContainerDark = Color(0xFFFFDBCF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF111315)
val onBackgroundDark = Color(0xFFE1E2E4)
val surfaceDark = Color(0xFF111315)
val onSurfaceDark = Color(0xFFE1E2E4)
val surfaceVariantDark = Color(0xFF43474E)
val onSurfaceVariantDark = Color(0xFFC3C6CF)
val outlineDark = Color(0xFF8D9199)
val outlineVariantDark = Color(0xFF43474E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E2E4)
val inverseOnSurfaceDark = Color(0xFF2E3132)
val inversePrimaryDark = Color(0xFF001E40)
val surfaceDimDark = Color(0xFF111315)
val surfaceBrightDark = Color(0xFF37393B)
val surfaceContainerLowestDark = Color(0xFF0C0E10)
val surfaceContainerLowDark = Color(0xFF191C1D)
val surfaceContainerDark = Color(0xFF1D2021)
val surfaceContainerHighDark = Color(0xFF282A2C)
val surfaceContainerHighestDark = Color(0xFF323537)

// Dark Medium Contrast
val primaryDarkMediumContrast = Color(0xFFAECCFF)
val onPrimaryDarkMediumContrast = Color(0xFF00192E)
val primaryContainerDarkMediumContrast = Color(0xFF6E92C7)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFF5EE554)
val onSecondaryDarkMediumContrast = Color(0xFF001E01)
val secondaryContainerDarkMediumContrast = Color(0xFF23AB24)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFBBA0)
val onTertiaryDarkMediumContrast = Color(0xFF2F0D00)
val tertiaryContainerDarkMediumContrast = Color(0xFFFF7D49)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF111315)
val onBackgroundDarkMediumContrast = Color(0xFFE1E2E4)
val surfaceDarkMediumContrast = Color(0xFF111315)
val onSurfaceDarkMediumContrast = Color(0xFFFAFAFC)
val surfaceVariantDarkMediumContrast = Color(0xFF43474E)
val onSurfaceVariantDarkMediumContrast = Color(0xFFC7CAD3)
val outlineDarkMediumContrast = Color(0xFF9FA3AB)
val outlineVariantDarkMediumContrast = Color(0xFF7F838B)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE1E2E4)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF282A2C)
val inversePrimaryDarkMediumContrast = Color(0xFF004984)
val surfaceDimDarkMediumContrast = Color(0xFF111315)
val surfaceBrightDarkMediumContrast = Color(0xFF37393B)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF070909)
val surfaceContainerLowDarkMediumContrast = Color(0xFF191C1D)
val surfaceContainerDarkMediumContrast = Color(0xFF1D2021)
val surfaceContainerHighDarkMediumContrast = Color(0xFF282A2C)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF323537)

// Dark High Contrast
val primaryDarkHighContrast = Color(0xFFFAFAFC)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFAECCFF)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFF0FFEA)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFF5EE554)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFFF9F8)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFFFBBA0)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF111315)
val onBackgroundDarkHighContrast = Color(0xFFE1E2E4)
val surfaceDarkHighContrast = Color(0xFF111315)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF43474E)
val onSurfaceVariantDarkHighContrast = Color(0xFFFAFAFC)
val outlineDarkHighContrast = Color(0xFFC7CAD3)
val outlineVariantDarkHighContrast = Color(0xFF9FA3AB)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE1E2E4)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF002A4F)
val surfaceDimDarkHighContrast = Color(0xFF111315)
val surfaceBrightDarkHighContrast = Color(0xFF37393B)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF191C1D)
val surfaceContainerDarkHighContrast = Color(0xFF1D2021)
val surfaceContainerHighDarkHighContrast = Color(0xFF282A2C)
val surfaceContainerHighestDarkHighContrast = Color(0xFF323537)

// Semantic Color Tokens for Status & Interaction
// Using Pitch Green for positive states (attendance/available)
val attendingColor = Color(0xFF75FF68) // secondary_container_light
val skillBeginnerTint = Color(0xFFD4E3FF) // primary_fixed_dim equivalent
val skillIntermediateTint = Color(0xFF75FF68) // secondary_fixed_dim equivalent
val skillEliteTint = Color(0xFFFFDBCF) // tertiary_fixed_dim equivalent

// Glassmorphism & Ambient Tinting
// Use these for overlays and floating components
val surfaceTintLight = Color(0xFF001E40) // primary at 10% opacity for glass effect
val surfaceTintDark = Color(0xFFA6C8FF) // primaryDark at 10% opacity for glass effect
val ambientShadow = Color(0xFF191C1D) // onSurface at 4% opacity, 32px blur
